# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Lint"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - name: Install dependencies
        run: npm install
      # Add or replace any other lints here
      - name: Rubocop
        run: bundle exec rubocop
      - name: ERB-Lint
        run: bundle exec erblint --lint-all app/
      - name: ESLint
        run: npx eslint ./app/javascript
